id: IA9A96121
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T11:38:58+00:00'
last_modified: '2022-06-07T17:35:09.673529+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1041
  title: གསུང་ཐོར་བུ། བཅོམ་ལྡན་རིག་པའི་རལ་གྲི
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '7273':
      image_group_id: I1CZ1397
      title: ''
      total_pages: 622
      order: 1
      base_file: 7273.txt
    2F59:
      image_group_id: I1CZ1398
      title: ''
      total_pages: 462
      order: 2
      base_file: 2F59.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
